# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, async, cairo, dataDefault, gtk3, lens, mtl, parsec, pipes
, pipesConcurrency, text, yiRope
}:

cabal.mkDerivation (self: {
  pname = "Skell";
  version = "0.1.0.0";
  src = ./.;
  isLibrary = true;
  isExecutable = true;
  buildDepends = [
    async cairo dataDefault gtk3 lens mtl parsec pipes pipesConcurrency
    text yiRope
  ];
  meta = {
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
